name: ar_explorer
description: "AR Explorer – Interactive mobile learning platform for Augmented Reality concepts."
publish_to: 'none'

version: 1.1.1+7

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  gal: ^2.3.2
  google_mobile_ads: ^7.0.0
  in_app_review: ^2.0.11
  package_info_plus: ^9.0.0
  in_app_purchase: ^3.2.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_local_notifications: ^21.0.0
  timezone: 0.11.0
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/AR vs VR vs MR vs XR/
    - assets/images/Real World Examples vs Common Misconceptions/
    - assets/images/evolution of spatial computing in augmented reality/
    - assets/images/Why coordinate systems in AR/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

