import '../models/quiz_model.dart';

// ═══════════════════════════════════════════════════════════════════
//  QUIZ DATA — Interview Time Assessments
// ═══════════════════════════════════════════════════════════════════

final Map<String, Quiz> allQuizzes = {
  // ───────────────────────────────────────────────────────────────
  //  QUIZ — AR Basics (Definitions)
  // ───────────────────────────────────────────────────────────────
  'quiz_intro_basics': Quiz(
    id: 'quiz_intro_basics',
    moduleId: 'intro_ar_basics',
    title: 'Checkup: AR Basics & Vocabulary',
    questions: [
      const QuizQuestion(
        id: 'q_intro_1',
        question: 'Which statement best describes Augmented Reality (AR)?',
        options: [
          'A fully virtual world that replaces reality',
          'Digital content overlaid onto the real world in real time',
          'Any 3D animation rendered on a screen',
          'A 360° video without interaction',
        ],
        correctIndex: 1,
        explanation:
            'AR keeps the real world visible and adds digital content that responds to your movement.',
      ),
      const QuizQuestion(
        id: 'q_intro_2',
        question: 'What is the MAIN difference between AR and VR?',
        options: [
          'AR runs only on phones, VR only on PCs',
          'AR shows the real world with digital overlays, VR hides the real world',
          'AR uses less battery than VR',
          'VR always uses hand controllers',
        ],
        correctIndex: 1,
        explanation:
            'In VR you only see a virtual world. In AR the physical environment is still your primary reference.',
      ),
      const QuizQuestion(
        id: 'q_intro_3',
        question: 'Which term is an umbrella that includes AR, VR and MR?',
        options: ['XR', 'GPU', 'SLAM', 'FOV'],
        correctIndex: 0,
        explanation:
            'XR (Extended Reality) is a broad label that covers AR, VR and MR.',
      ),
      const QuizQuestion(
        id: 'q_intro_4',
        question:
            'Which of the following is the BEST example of a true AR experience?',
        options: [
          'A 3D logo always centered on the screen, not tied to the environment',
          'A face filter that stays perfectly locked to the user’s head as they move',
          'A 360° video playing on a flat screen',
          'A static 3D image inside a PDF',
        ],
        correctIndex: 1,
        explanation:
            'Tracking and registration are key: the digital content must stay aligned with real-world motion.',
      ),
      const QuizQuestion(
        id: 'q_intro_5',
        question: 'Which misconception is MOST common among beginners?',
        options: [
          'AR is only for enterprise',
          'AR always requires a headset and cannot run on phones',
          'AR has no use in education',
          'AR and VR are mathematically unrelated',
        ],
        correctIndex: 1,
        explanation:
            'Many powerful AR solutions run entirely on smartphones and tablets.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 1 — Introduction to AR
  // ───────────────────────────────────────────────────────────────
  'quiz_intro': Quiz(
    id: 'quiz_intro',
    moduleId: 'mod_intro',
    title: 'Mastery Interview: Spatial AR',
    questions: [
      const QuizQuestion(
        id: 'q_milgram_spectrum',
        question:
            'According to Paul Milgram, what does Mixed Reality (MR) encompass?',
        options: [
          'Only high-end VR headsets',
          'The entire spectrum between the Physical World and Virtual Reality',
          'Only mobile phone AR apps',
          '3D rendering without tracking',
        ],
        correctIndex: 1,
        explanation:
            'MR is the broader technical term for the entire middle ground where physical and digital objects co-exist and interact.',
      ),
      const QuizQuestion(
        id: 'q_hmd_performance',
        question:
            'Why do industrial sectors prefer Head-Mounted Displays (HMDs) over Handheld AR for guided assembly?',
        options: [
          'HMDs are cheaper to deploy',
          'HMDs offer hands-free workflows and higher "presence"',
          'HMDs have better battery life',
          'HMDs do not require a Wi-Fi connection',
        ],
        correctIndex: 1,
        explanation:
            'Hands-free operation is critical for industrial workers who must use their hands for assembly while viewing digital instructions.',
      ),
      const QuizQuestion(
        id: 'q_webar_friction',
        question: 'What is the "Friction Factor" in mobile AR deployment?',
        options: [
          'The physical drag of the device',
          'The significant user drop-off caused by requiring a native app download',
          'The heat generated by the GPU',
          'The difficulty of scanning a QR code',
        ],
        correctIndex: 1,
        explanation:
            'WebAR mitigates friction by allowing users to access content instantly through a browser without an App Store download.',
      ),
      const QuizQuestion(
        id: 'q_wasm_webar',
        question:
            'How do WebAR frameworks like 8th Wall maintain 60FPS tracking within a browser sandbox?',
        options: [
          'By reducing the screen resolution',
          'By using WebAssembly (Wasm) for computer vision tasks',
          'By disabling the camera feed',
          'By using cloud-only rendering',
        ],
        correctIndex: 1,
        explanation:
            'Wasm allows near-native execution speed for complex tracking algorithms within the browser environment.',
      ),
      const QuizQuestion(
        id: 'q_hybrid_occlusion',
        question: 'What is "Z-fighting" in the context of AR rendering?',
        options: [
          'Two users competing for a shared anchor',
          'Two surfaces at the same depth flickering as they compete for rendering priority',
          'A failure in the accelerometer',
          'Low battery causing screen lag',
        ],
        correctIndex: 1,
        explanation:
            'Z-fighting is a visual artifact where the engine cannot determine which object is in front of the other due to identical depth values.',
      ),
      const QuizQuestion(
        id: 'q_asa_benefit',
        question:
            'What is a primary advantage of Azure Spatial Anchors (ASA) for large-scale enterprise?',
        options: [
          'It is free for all users',
          'It allows cloud-based persistence and multi-device cross-platform collaboration',
          'It increases the FOV of the headset',
          'It deletes old map data automatically',
        ],
        correctIndex: 1,
        explanation:
            'ASA enables multi-device shared AR by storing the spatial map in the cloud, allowing an iOS device and a HoloLens to see the same content.',
      ),
      const QuizQuestion(
        id: 'q_relocalization',
        question: 'What happens during "Relocalization" in a SLAM system?',
        options: [
          'The device restarts its OS',
          'The system recognizes a known environment and aligns its coordinate system with a stored map',
          'The camera switches to infrared mode',
          'The GPS coordinates are updated',
        ],
        correctIndex: 1,
        explanation:
            'Relocalization is the "Aha!" moment when the device recognizes where it is based on previously mapped features.',
      ),
      const QuizQuestion(
        id: 'q_progressive_disclosure',
        question:
            'What does the UX principle of "Progressive Disclosure" aim to solve in AR?',
        options: [
          'High hardware latency',
          'HUD clutter and cognitive overload',
          'Low battery life',
          'Slow internet speeds',
        ],
        correctIndex: 1,
        explanation:
            'By revealing details only upon demand, you keep the user’s field of view clear and focus their attention on critical tasks.',
      ),
      const QuizQuestion(
        id: 'q_klm_visionpro',
        question:
            'In the KLM Royal Dutch Airlines case study, why was AR used on the Apple Vision Pro?',
        options: [
          'To entertain passengers on long flights',
          'To train technicians on complex engine repairs using full-fidelity 3D models',
          'To book tickets faster',
          'To scan luggage weights',
        ],
        correctIndex: 1,
        explanation:
            'AR training with high-fidelity 3D overlays significantly reduces errors and accelerates learning in complex mechanical tasks.',
      ),
      const QuizQuestion(
        id: 'q_registration_failure',
        question:
            'What is the technical term for virtual objects "sliding" or "jumping" due to tracking errors?',
        options: ['Latency', 'Drift', 'Z-Fighting', 'Ghosting'],
        correctIndex: 1,
        explanation:
            'Drift occurs when the tracking system accumulates small errors, causing the virtual content to lose its alignment with the physical world.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 2 — Technical Concepts
  // ───────────────────────────────────────────────────────────────
  'quiz_tech': Quiz(
    id: 'quiz_tech',
    moduleId: 'mod_tech',
    title: 'Interview Time: Technical Concepts',
    questions: [
      const QuizQuestion(
        id: 'q2_1',
        question: 'What is Visual-Inertial Odometry (VIO)?',
        options: [
          'A technique for rendering 3D models',
          'Fusion of camera and IMU data for 6DoF tracking',
          'A method to compress AR textures',
          'A network protocol for cloud anchors',
        ],
        correctIndex: 1,
        explanation:
            'VIO combines visual feature tracking from the camera with inertial measurement unit (IMU) data for precise 6 degrees of freedom tracking.',
      ),
      const QuizQuestion(
        id: 'q2_2',
        question: 'What does SLAM stand for?',
        options: [
          'Spatial Layout and Mapping',
          'Simultaneous Localization and Mapping',
          'Surface Light and Material',
          'Sensor-Level Augmented Modeling',
        ],
        correctIndex: 1,
        explanation:
            'SLAM stands for Simultaneous Localization and Mapping — building a map of the environment while tracking position within it.',
      ),
      const QuizQuestion(
        id: 'q2_3',
        question:
            'Which type of surface is MOST challenging for plane detection?',
        options: [
          'Wooden desk with visible grain',
          'Carpet with a pattern',
          'Smooth, transparent glass table',
          'Tiled floor with distinct tiles',
        ],
        correctIndex: 2,
        explanation:
            'Smooth, reflective, or transparent surfaces lack detectable features and are very challenging for plane detection algorithms.',
      ),
      const QuizQuestion(
        id: 'q2_4',
        question: 'What is the purpose of loop closure in SLAM?',
        options: [
          'To close the AR session',
          'To correct accumulated drift when revisiting a known area',
          'To lock the frame rate at 60 FPS',
          'To finalize the 3D model export',
        ],
        correctIndex: 1,
        explanation:
            'Loop closure detects when the device returns to a previously mapped area and corrects the accumulated drift in the map.',
      ),
      const QuizQuestion(
        id: 'q2_5',
        question:
            'Which feature detector is known for being extremely fast at corner detection?',
        options: ['SIFT', 'ORB', 'FAST', 'SURF'],
        correctIndex: 2,
        explanation:
            'FAST (Features from Accelerated Segment Test) is designed for rapid corner detection, making it suitable for real-time AR.',
      ),
      const QuizQuestion(
        id: 'q2_6',
        question: 'Environmental HDR in light estimation provides:',
        options: [
          'Only ambient brightness',
          'A full spherical lighting map for reflections and shadows',
          'Only color temperature',
          'A binary light/dark indicator',
        ],
        correctIndex: 1,
        explanation:
            'Environmental HDR provides a complete spherical environment map that enables realistic reflections, specular highlights, and shadows on virtual objects.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 3 — Development
  // ───────────────────────────────────────────────────────────────
  'quiz_dev': Quiz(
    id: 'quiz_dev',
    moduleId: 'mod_dev',
    title: 'Interview Time: AR Development',
    questions: [
      const QuizQuestion(
        id: 'q3_1',
        question: 'In Vuforia, what does "Extended Tracking" allow?',
        options: [
          'Tracking targets from a greater distance',
          'Content persistence even when the target leaves the camera view',
          'Tracking multiple targets simultaneously',
          'Higher resolution target images',
        ],
        correctIndex: 1,
        explanation:
            'Extended Tracking allows AR content to remain visible and tracked even after the original image target is no longer in the camera\'s field of view.',
      ),
      const QuizQuestion(
        id: 'q3_2',
        question: 'In ARCore, what is the purpose of a Raycast (hit test)?',
        options: [
          'To measure the brightness of the scene',
          'To find intersections between a 2D screen point and real-world geometry',
          'To compress the camera feed',
          'To transfer data to the cloud',
        ],
        correctIndex: 1,
        explanation:
            'Raycasting sends a virtual ray from a 2D screen point into the 3D world to detect intersections with tracked planes or feature points.',
      ),
      const QuizQuestion(
        id: 'q3_3',
        question: 'Which AR Foundation manager handles surface detection?',
        options: [
          'ARAnchorManager',
          'ARRaycastManager',
          'ARPlaneManager',
          'ARCameraManager',
        ],
        correctIndex: 2,
        explanation:
            'ARPlaneManager is responsible for detecting and visualizing planes (horizontal and vertical surfaces) in the real world.',
      ),
      const QuizQuestion(
        id: 'q3_4',
        question:
            'Why should you filter hit results by trackable type in ARCore?',
        options: [
          'To reduce battery usage',
          'To prioritize stable plane hits over less reliable feature point hits',
          'To enable cloud anchors',
          'To improve camera resolution',
        ],
        correctIndex: 1,
        explanation:
            'Plane hits provide more stable and reliable placement than feature point hits. Filtering ensures better user experience.',
      ),
      const QuizQuestion(
        id: 'q3_5',
        question: 'What does AR Session Origin define in AR Foundation?',
        options: [
          'The UI layout of the application',
          'The transform space and origin point for AR content',
          'The network configuration for cloud features',
          'The target image database location',
        ],
        correctIndex: 1,
        explanation:
            'AR Session Origin defines the world coordinate system\'s origin point and transform space in which AR content is placed.',
      ),
      const QuizQuestion(
        id: 'q3_6',
        question:
            'What should your app do when Vuforia reports a TRACKING_LOST state?',
        options: [
          'Immediately close the app',
          'Continue rendering content normally',
          'Show user guidance to re-find the target',
          'Restart the device',
        ],
        correctIndex: 2,
        explanation:
            'When tracking is lost, the app should provide user guidance (e.g., "Point camera at the target") to help recover tracking.',
      ),
      const QuizQuestion(
        id: 'q3_7',
        question: 'Which framework is Apple\'s modern standard for AR rendering?',
        options: [
          'SceneKit',
          'RealityKit',
          'Metal',
          'UIKit',
        ],
        correctIndex: 1,
        explanation: 'RealityKit is purpose-built for AR, offering native LiDAR support and physically-based rendering.',
      ),
      const QuizQuestion(
        id: 'q3_8',
        question: 'What does "arcore:required" in the AndroidManifest do?',
        options: [
          'Makes the app run faster',
          'Filters out non-AR compatible devices from Google Play Store',
          'Requests camera permission automatically',
          'Enables 60 FPS mode',
        ],
        correctIndex: 1,
        explanation: '"Required" ensures the app is only visible to users whose devices support ARCore.',
      ),
      const QuizQuestion(
        id: 'q3_9',
        question: 'What is the "AR Manager" pattern used for?',
        options: [
          'Managing user subscriptions',
          'Separating spatial logic from UI logic',
          'Scaling 3D models',
          'Optimizing battery life',
        ],
        correctIndex: 1,
        explanation: 'The AR Manager acts as a single controller for the AR session, keeping your UI code clean and decoupled.',
      ),
      const QuizQuestion(
        id: 'q3_10',
        question: 'Where must you define NSCameraUsageDescription on iOS?',
        options: [
          'AppDelegate.swift',
          'Info.plist',
          'Podfile',
          'Assets.xcassets',
        ],
        correctIndex: 1,
        explanation: 'iOS requires this string in the Info.plist to explain why the app needs camera access, or it will crash.',
      ),
      const QuizQuestion(
        id: 'q3_11',
        question: 'Which feature allows virtual objects to render BEHIND people?',
        options: [
          'Depth API / People Occlusion',
          'Z-Fighting',
          'LOD (Level of Detail)',
          'Frustum Culling',
        ],
        correctIndex: 0,
        explanation: 'People Occlusion uses ML or LiDAR to segment humans, allowing virtual content to be hidden behind them.',
      ),
      const QuizQuestion(
        id: 'q3_12',
        question: 'Can you test ARCore tracking in the standard Android Emulator?',
        options: [
          'Yes, it works perfectly',
          'No, AR requires physical sensors and camera input',
          'Yes, but only in grayscale',
          'Yes, using a special "AR Mode" plugin',
        ],
        correctIndex: 1,
        explanation: 'While basic logic can be tested in simulators, true AR tracking requires physical hardware sensors (IMU) and a real camera.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 4 — Stabilization & Performance
  // ───────────────────────────────────────────────────────────────
  'quiz_stab': Quiz(
    id: 'quiz_stab',
    moduleId: 'mod_stab',
    title: 'Interview Time: Stabilization & Performance',
    questions: [
      const QuizQuestion(
        id: 'q4_1',
        question:
            'What is the minimum frame rate recommended for a comfortable AR experience?',
        options: ['24 FPS', '30 FPS', '60 FPS', '120 FPS'],
        correctIndex: 2,
        explanation:
            'AR applications should maintain 60 FPS to prevent jitter and motion sickness. Lower frame rates cause visible tracking artifacts.',
      ),
      const QuizQuestion(
        id: 'q4_2',
        question: 'What causes positional drift in AR?',
        options: [
          'Too many 3D models in the scene',
          'Accumulated small tracking errors over time',
          'Incorrect texture formats',
          'High screen resolution',
        ],
        correctIndex: 1,
        explanation:
            'Drift occurs when small errors in position estimation compound over time, causing virtual content to gradually shift from its intended position.',
      ),
      const QuizQuestion(
        id: 'q4_3',
        question: 'Which technique helps reduce rendering overhead in AR?',
        options: [
          'Increasing polygon count for realism',
          'Using real-time ray tracing',
          'Using LOD (Level of Detail) for 3D models',
          'Adding more light sources',
        ],
        correctIndex: 2,
        explanation:
            'LOD reduces polygon count based on distance from the camera, significantly reducing rendering overhead while maintaining visual quality.',
      ),
      const QuizQuestion(
        id: 'q4_4',
        question: 'Why should you limit the number of active anchors?',
        options: [
          'Anchors use significant storage space',
          'Each anchor adds computational overhead for tracking',
          'Anchors slow down the camera feed',
          'The OS limits anchor count to 5',
        ],
        correctIndex: 1,
        explanation:
            'Each active anchor requires computational resources to maintain and update its pose. Too many anchors degrade tracking performance.',
      ),
      const QuizQuestion(
        id: 'q4_5',
        question:
            'What should your app display when tracking state is PAUSED/LIMITED?',
        options: [
          'A blank screen',
          'A loading spinner replacing the camera feed',
          'The camera feed with a cautionary overlay message',
          'A settings menu',
        ],
        correctIndex: 2,
        explanation:
            'Never hide the camera feed. Show a translucent guidance overlay to help the user restore tracking without disorienting them.',
      ),
      const QuizQuestion(
        id: 'q4_6',
        question:
            'Which texture compression format is recommended for mobile AR?',
        options: ['PNG (uncompressed)', 'BMP', 'ASTC/ETC2', 'TIFF'],
        correctIndex: 2,
        explanation:
            'ASTC and ETC2 are GPU-native compressed formats optimized for mobile devices, reducing memory usage while maintaining quality.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ — Coordinate Systems Foundations
  // ───────────────────────────────────────────────────────────────
  'quiz_foundations_coords': Quiz(
    id: 'quiz_foundations_coords',
    moduleId: 'foundations_coordinate_systems',
    title: 'Checkup: Coordinate Systems for AR',
    questions: [
      const QuizQuestion(
        id: 'q_coords_1',
        question: 'What is World Space in AR?',
        options: [
          'A 2D grid where UI buttons live',
          'A stable 3D coordinate system tied to the physical environment',
          'The coordinate system of the phone’s screen pixels',
          'The local axes of a single 3D model',
        ],
        correctIndex: 1,
        explanation:
            'World space represents the real environment; anchors and planes are defined there.',
      ),
      const QuizQuestion(
        id: 'q_coords_2',
        question: 'Camera Space is best described as:',
        options: [
          'A space where the origin is at the world center of the room',
          'A space centered on the device camera, looking forward',
          'A coordinate system used only for UI menus',
          'A GPS-based global coordinate system',
        ],
        correctIndex: 1,
        explanation:
            'In camera space, the origin sits at the camera and the forward axis points along its viewing direction.',
      ),
      const QuizQuestion(
        id: 'q_coords_3',
        question:
            'Screen Space coordinates are MOST directly used for which action?',
        options: [
          'Defining the world position of anchors',
          'Describing the user’s GPS location outdoors',
          'Handling touch input positions and UI layout',
          'Storing 3D meshes in files',
        ],
        correctIndex: 2,
        explanation:
            'Screen space is a 2D coordinate system for pixels and UI elements — and for touch positions before they are converted to rays.',
      ),
      const QuizQuestion(
        id: 'q_coords_4',
        question:
            'Placing an object in camera space instead of world space will MOST LIKELY result in:',
        options: [
          'The object staying fixed in the room even if you move',
          'The object “sticking” to the camera and moving with your phone/head',
          'The object becoming invisible',
          'The app crashing immediately',
        ],
        correctIndex: 1,
        explanation:
            'Content in camera space follows the camera; it does not stay anchored to the room.',
      ),
      const QuizQuestion(
        id: 'q_coords_5',
        question:
            'Which question should you ask first when debugging a weird AR position/rotation?',
        options: [
          '“Is my texture compressed correctly?”',
          '“How many draw calls do I have?”',
          '“In which coordinate system am I right now?”',
          '“What is the FOV of the headset?”',
        ],
        correctIndex: 2,
        explanation:
            'Most early bugs come from mixing spaces. Knowing which coordinate system you are in is step one.',
      ),
    ],
  ),
  
  // ───────────────────────────────────────────────────────────────
  //  QUIZ 6 — Advanced AR Knowledge
  // ───────────────────────────────────────────────────────────────
  'quiz_advanced_ar': Quiz(
    id: 'quiz_advanced_ar',
    moduleId: 'mod_advanced',
    title: 'Advanced AR Knowledge',
    passingScore: 70,
    questions: [
      const QuizQuestion(
        id: 'q_adv_1',
        question: 'What is the main benefit of LiDAR in AR headsets?',
        options: [
          'It provides realistic sound emulation',
          'It generates an instant, high-fidelity 3D mesh of the environment',
          'It replaces the need for a front camera',
          'It allows the headset to project holograms into thin air',
        ],
        correctIndex: 1,
        explanation: 'LiDAR uses light pulses to measure distance, instantly creating a precise 3D mesh for accurate occlusion and physics.',
      ),
      const QuizQuestion(
        id: 'q_adv_2',
        question: 'What is Dynamic Occlusion?',
        options: [
          'Hiding virtual objects behind a static scanned mesh',
          'Using per-frame depth data to hide virtual objects behind moving physical objects like people',
          'A networking technique to hide latency',
          'Dimming the screen to save battery',
        ],
        correctIndex: 1,
        explanation: 'Dynamic occlusion leverages machine learning or LiDAR to infer depth per-frame, hiding AR objects behind moving people or objects.',
      ),
      const QuizQuestion(
        id: 'q_adv_3',
        question: 'Which of the following creates a "Shared Experience" rather than just Persistence?',
        options: [
          'Leaving a 3D note for someone to find tomorrow',
          'Two users in the same room seeing the same virtual object in real-time',
          'Saving an offline map of your living room',
          'Reducing rendering resolution for better performance',
        ],
        correctIndex: 1,
        explanation: 'Shared experiences involve real-time synchronization between multiple devices in the same physical space.',
      ),
      const QuizQuestion(
        id: 'q_adv_4',
        question: 'What is a spatial anchor?',
        options: [
          'A physical QR code on the wall',
          'A fixed coordinate in the real world that a SLAM system tracks over time',
          'The focal length of the camera',
          'A UI button that stays at the bottom of the screen',
        ],
        correctIndex: 1,
        explanation: 'Spatial anchors provide a common reference point in the physical world to tie virtual objects to.',
      ),
      const QuizQuestion(
        id: 'q_adv_5',
        question: 'What happens when a SLAM system "relocalizes"?',
        options: [
          'It changes the language of the UI',
          'It uses GPS to find its position',
          'It recognizes previously mapped visual features to determine its current location',
          'It disconnects from the internet',
        ],
        correctIndex: 2,
        explanation: 'Relocalization is the process of comparing current camera frames to a saved map to regain tracking after it was lost or closed.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 7 — WebAR
  // ───────────────────────────────────────────────────────────────
  'quiz_webar': Quiz(
    id: 'quiz_webar',
    moduleId: 'mod_webar', // Note: using mod_webar to match the ID in modules_data if missing. (assuming mod_webar)
    title: 'WebAR Fundamentals Quiz',
    passingScore: 70,
    questions: [
      const QuizQuestion(
        id: 'q_webar_1',
        question: 'What is the primary advantage of WebAR over native apps?',
        options: [
          'Higher performance tracking',
          'Zero installation friction, running directly in the browser',
          'Full access to LiDAR sensors',
          'Offline capabilities out-of-the-box',
        ],
        correctIndex: 1,
        explanation: 'WebAR eliminates the need for app store downloads, making it ideal for marketing and quick engagements.',
      ),
      const QuizQuestion(
        id: 'q_webar_2',
        question: 'Which browser API is the emerging standard for native browser AR/VR?',
        options: [
          'WebGL',
          'WebXR Device API',
          'HTML5 Canvas',
          'WebRTC',
        ],
        correctIndex: 1,
        explanation: 'The WebXR Device API is the W3C standard for accessing AR and VR capabilities natively via the browser.',
      ),
      const QuizQuestion(
        id: 'q_webar_3',
        question: 'What is WebAssembly (Wasm) primarily used for in WebAR?',
        options: [
          'Styling UI buttons',
          'Running complex computer vision algorithms at near-native speed',
          'Connecting to databases',
          'Playing audio files',
        ],
        correctIndex: 1,
        explanation: 'Wasm allows C/C++ computer vision libraries (like SLAM engines) to run in the browser with performance close to native apps.',
      ),
      const QuizQuestion(
        id: 'q_webar_4',
        question: 'Why is model compression (like Draco) critical for WebAR?',
        options: [
          'To increase the polygon count',
          'To minimize download times over cellular networks',
          'To make the models look more realistic',
          'Because WebGL only supports compressed files',
        ],
        correctIndex: 1,
        explanation: 'Because the user isn\'t downloading an app beforehand, all 3D assets must be downloaded on-the-fly. Small file sizes are essential.',
      ),
      const QuizQuestion(
        id: 'q_webar_5',
        question: 'What does 8th Wall provide that native WebXR does not?',
        options: [
          'A proprietary 3D rendering engine',
          'Cloud hosting for HTML files',
          'SLAM tracking that works on almost any smartphone browser without requiring native OS-level AR support',
          'Access to the phone\'s battery API',
        ],
        correctIndex: 2,
        explanation: '8th Wall\'s custom SLAM engine runs purely in JavaScript/Wasm, giving it broader device compatibility than WebXR which requires ARCore/ARKit underneath.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 8 — OpenXR Standard
  // ───────────────────────────────────────────────────────────────
  'quiz_openxr': Quiz(
    id: 'quiz_openxr',
    moduleId: 'mod_openxr',
    title: 'OpenXR Quiz',
    passingScore: 70,
    questions: [
      const QuizQuestion(
        id: 'q_openxr_1',
        question: 'What problem does OpenXR primarily solve?',
        options: [
          'Low frame rates in VR',
          'API fragmentation across different AR/VR headsets and platforms',
          'Poor 3D model compression',
          'High battery consumption',
        ],
        correctIndex: 1,
        explanation: 'Before OpenXR, developers had to write custom code for Oculus, SteamVR, WMR, etc. OpenXR provides a single standard API.',
      ),
      const QuizQuestion(
        id: 'q_openxr_2',
        question: 'Which organization develops and maintains the OpenXR standard?',
        options: [
          'Google',
          'Apple',
          'The Khronos Group',
          'Meta',
        ],
        correctIndex: 2,
        explanation: 'The Khronos Group (which also manages Vulkan and WebGL) maintains OpenXR as an open, royalty-free standard.',
      ),
      const QuizQuestion(
        id: 'q_openxr_3',
        question: 'In OpenXR architecture, what does the Application interact with directly?',
        options: [
          'The GPU hardware',
          'The OpenXR API',
          'The headset firmware',
          'The display drivers',
        ],
        correctIndex: 1,
        explanation: 'The application calls the OpenXR API, which is then translated by the OpenXR Runtime into hardware-specific operations.',
      ),
      const QuizQuestion(
        id: 'q_openxr_4',
        question: 'What happens during the OpenXR Action System binding phase?',
        options: [
          'Textures are bound to materials',
          'Network sockets are opened',
          'Logical actions (like "jump") are mapped to physical hardware inputs (like "A button")',
          'The application binary is linked',
        ],
        correctIndex: 2,
        explanation: 'The Action System abstracts input. Instead of querying a specific button, the app asks if "jump" happened, and the runtime handles the mapping.',
      ),
      const QuizQuestion(
        id: 'q_openxr_5',
        question: 'What is an OpenXR "Extension"?',
        options: [
          'A browser plugin to play VR',
          'A cable that connects a headset to a PC',
          'An optional feature (like hand tracking) that hardware vendors can support on top of the core API',
          'A 3D model format',
        ],
        correctIndex: 2,
        explanation: 'Extensions allow vendors to introduce cutting-edge features before they become part of the core OpenXR standard.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 9 — The AR Cloud
  // ───────────────────────────────────────────────────────────────
  'quiz_ar_cloud': Quiz(
    id: 'quiz_ar_cloud',
    moduleId: 'mod_ar_cloud',
    title: 'AR Cloud Quiz',
    passingScore: 70,
    questions: [
      const QuizQuestion(
        id: 'q_arcloud_1',
        question: 'What is the "AR Cloud"?',
        options: [
          'Storing 3D models on AWS or Azure',
          'A persistent, real-time shared 3D map of the physical world',
          'Streaming video from a server',
          'A weather application for AR headsets',
        ],
        correctIndex: 1,
        explanation: 'The AR Cloud is the conceptual infrastructure that maps the world, allowing devices to share a common spatial understanding.',
      ),
      const QuizQuestion(
        id: 'q_arcloud_2',
        question: 'Which sequence correctly describes the AR Cloud workflow?',
        options: [
          'Download -> Render -> Display',
          'Map physical space -> Upload features -> Relocalize -> Sync state',
          'Login -> Scan QR -> Show ad',
          'Turn on GPS -> Get coordinates -> Show map',
        ],
        correctIndex: 1,
        explanation: 'Devices must map the environment, share key features to a cloud backend, allow others to relocalize against that map, and then synchronize the states of virtual objects.',
      ),
      const QuizQuestion(
        id: 'q_arcloud_3',
        question: 'What is a "Digital Twin" in the context of the AR Cloud?',
        options: [
          'A backup copy of your hard drive',
          'A virtual replica of a physical space or object updated in near real-time',
          'An avatar meant to look exactly like the user',
          'Two identical AR headsets',
        ],
        correctIndex: 1,
        explanation: 'Digital twins are highly accurate digital models of physical environments, often used in enterprise for simulation and spatial computing.',
      ),
      const QuizQuestion(
        id: 'q_arcloud_4',
        question: 'Why is standard GPS insufficient for the AR Cloud?',
        options: [
          'GPS is too expensive',
          'GPS cannot be used indoors and lacks 6DoF orientation and millimeter precision',
          'GPS data cannot be sent over the internet',
          'GPS drains the battery too fast',
        ],
        correctIndex: 1,
        explanation: 'GPS offers meter-level accuracy globally, but AR requires centimeter-level 6DoF accuracy (position and rotation), especially indoors where GPS fails.',
      ),
      const QuizQuestion(
        id: 'q_arcloud_5',
        question: 'What is the primary privacy concern associated with the AR Cloud?',
        options: [
          'It records audio constantly',
          'It requires users to upload potentially sensitive point clouds or images of private spaces to remote servers',
          'It forces users to use their real names',
          'It tracks the websites users visit',
        ],
        correctIndex: 1,
        explanation: 'Building the AR cloud requires cameras to scan environments. Uploading these visual features raises severe privacy and security concerns for private spaces.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 10 — SLAM Deep Dive
  // ───────────────────────────────────────────────────────────────
  'quiz_slam_deepdive': Quiz(
    id: 'quiz_slam_deepdive',
    moduleId: 'mod_slam_deepdive',
    title: 'SLAM Deep Dive Quiz',
    passingScore: 70,
    questions: [
      const QuizQuestion(
        id: 'q_slam_1',
        question: 'What sensors are primarily fused in typical mobile VIO (Visual-Inertial Odometry)?',
        options: [
          'Camera and GPS',
          'Camera and IMU (Accelerometer/Gyroscope)',
          'LiDAR and Microphone',
          'WiFi and Bluetooth',
        ],
        correctIndex: 1,
        explanation: 'VIO fuses sparse visual feature tracking from the camera with high-frequency inertial data from the IMU to calculate pose.',
      ),
      const QuizQuestion(
        id: 'q_slam_2',
        question: 'In SLAM feature extraction, what are the two components of a feature?',
        options: [
          'Color and Brightness',
          'Keypoint (location) and Descriptor (identity summary)',
          'Vector and Normal',
          'X coordinates and Y coordinates',
        ],
        correctIndex: 1,
        explanation: 'A keypoint identifies the pixel location of a feature (like a corner), while the descriptor mathematically summarizes its visual neighborhood so it can be matched across frames.',
      ),
      const QuizQuestion(
        id: 'q_slam_3',
        question: 'What mathematical technique is crucial for rejecting bad feature matches (outliers) in SLAM?',
        options: [
          'Fast Fourier Transform',
          'Newton-Raphson method',
          'RANSAC (Random Sample Consensus)',
          'K-Means clustering',
        ],
        correctIndex: 2,
        explanation: 'RANSAC iteratively selects subsets of data to find the mathematical model (e.g., camera movement) that most features agree with, rejecting the outliers.',
      ),
      const QuizQuestion(
        id: 'q_slam_4',
        question: 'What happens during SLAM "Bundle Adjustment"?',
        options: [
          'The app compresses 3D models into a bundle',
          'It simultaneously refines the 3D coordinates of the map points and the camera poses to minimize reprojection error',
          'It packages the tracking data to send to the cloud',
          'It adjusts the screen brightness based on ambient light',
        ],
        correctIndex: 1,
        explanation: 'Bundle adjustment is an optimization step that takes all recent camera poses and mapped points and mathematically adjusts them to find the most accurate global solution.',
      ),
      const QuizQuestion(
        id: 'q_slam_5',
        question: 'What is essentially "Scale Ambiguity" in Monocular (single camera) SLAM?',
        options: [
          'Not knowing if an object is large and far away, or small and close',
          'The camera being unable to focus',
          'The inability to read QR codes at a distance',
          'Floating point math errors',
        ],
        correctIndex: 0,
        explanation: 'A single camera alone cannot determine absolute real-world scale. It requires IMU data (accelerometer) or a known physical reference to establish true scale.',
      ),
    ],
  ),

  // ───────────────────────────────────────────────────────────────
  //  QUIZ 11 — Performance Profiling
  // ───────────────────────────────────────────────────────────────
  'quiz_performance': Quiz(
    id: 'quiz_performance',
    moduleId: 'mod_performance',
    title: 'Performance Profiling Quiz',
    passingScore: 70,
    questions: [
      const QuizQuestion(
        id: 'q_perf_1',
        question: 'What is a "Draw Call"?',
        options: [
          'A user taping the screen to draw a line',
          'A command from the CPU to the GPU to render a set of polygons with a specific material',
          'Downloading a texture from the internet',
          'Saving the current frame to the camera roll',
        ],
        correctIndex: 1,
        explanation: 'Draw calls are expensive. Every time a new material or object needs rendering, the CPU must prepare and send a draw call to the GPU.',
      ),
      const QuizQuestion(
        id: 'q_perf_2',
        question: 'What is the most effective way to reduce Draw Calls?',
        options: [
          'Increase the polygon count',
          'Lower the screen brightness',
          'Combine multiple textures into a single Texture Atlas (batching)',
          'Use higher resolution textures',
        ],
        correctIndex: 2,
        explanation: 'By combining multiple textures into an atlas, multiple objects can share the same material, allowing the CPU to send them to the GPU in a single draw call.',
      ),
      const QuizQuestion(
        id: 'q_perf_3',
        question: 'What is Thermal Throttling?',
        options: [
          'The device lowering its CPU/GPU clock speeds to prevent overheating',
          'A feature that warms up the battery in cold weather',
          'A rendering technique for fire effects',
          'Network speed reduction',
        ],
        correctIndex: 0,
        explanation: 'AR is extremely demanding. When a phone overheats, the OS throttles the processor, causing frame rates to drop drastically (stuttering).',
      ),
      const QuizQuestion(
        id: 'q_perf_4',
        question: 'Which tool would you use to profile CPU and Memory usage in a Unity AR Foundation project?',
        options: [
          'Google Chrome DevTools',
          'Unity Profiler',
          'Adobe Photoshop',
          'Postman',
        ],
        correctIndex: 1,
        explanation: 'The Unity Profiler provides deep insights into CPU time, GPU rendering, memory allocation, and garbage collection spikes.',
      ),
      const QuizQuestion(
        id: 'q_perf_5',
        question: 'Why are transparent (alpha-blended) materials bad for mobile AR performance?',
        options: [
          'They don\'t look realistic',
          'They cause "overdraw" because the GPU must render the transparent pixels and the pixels behind them multiple times',
          'Transparencies make the SLAM system fail',
          'They take up more disk space',
        ],
        correctIndex: 1,
        explanation: 'Overdraw occurs when a pixel on the screen is rendered multiple times in a single frame. Heavy use of transparencies (like dense particle effects) kills mobile GPU performance.',
      ),
    ],
  ),
};
